# Generated by Django 5.0.1 on 2024-02-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_halls_hall_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halls',
            old_name='hall_mrp',
            new_name='hall_mem',
        ),
    ]
