# Generated by Django 5.0.1 on 2024-02-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=50)),
                ('hall_mem', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=100)),
                ('coordinatename', models.CharField(max_length=50)),
                ('coordinateid', models.CharField(max_length=20)),
                ('totalmember', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=80)),
            ],
        ),
    ]
