# Generated by Django 4.2.6 on 2024-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_remove_booking_id_booking_hall_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hall_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
